name: Backup Devspaces

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  deploy_snapshots:
    uses: zensharp/outline-mirror/.github/workflows/deploy.yml@main
    strategy:
      matrix:
        ENVIRONMENT:
          - breegull
          - redmeat
          #- starcourt
          #0- sideshow
    with:
      ENVIRONMENT: ${{ matrix.ENVIRONMENT }}
    secrets:
      OUTLINE_INSTANCE_URL: ${{ secrets.OUTLINE_INSTANCE_URL }}
      OUTLINE_API_KEY: ${{ secrets.OUTLINE_API_KEY }}
      OUTPUT_REPO_URL: ${{ secrets.OUTPUT_REPO_URL }}
      OUTPUT_SSH_KEY: ${{ secrets.OUTPUT_SSH_KEY }}
